name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-repository:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_WORKSPACE: repository
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: supercharge/redis-github-action@1.8.0
      - run: npm ci
      - run: npm test

  test-indexer:
    needs: [test-repository]
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_WORKSPACE: indexer
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: supercharge/redis-github-action@1.8.0
      - run: npm ci
      - run: npm test

  test-api:
    needs: [test-repository]
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_WORKSPACE: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: supercharge/redis-github-action@1.8.0
      - run: npm ci
      - run: npm test

  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build monorepo Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=registry,ref=ghcr.io/filecoin-station/piece-indexer
          cache-to: type=inline

  deploy-indexer:
    if: github.ref == 'refs/heads/main'
    needs: [test-indexer, docker-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c indexer/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_INDEXER }}
      - if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          channel-id: alerts
          payload: |
            {
              "text": "Deployment of `${{ github.event.repository.name }}` failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Deployment of `${{ github.event.repository.name }}` failed>*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  deploy-api:
    if: github.ref == 'refs/heads/main'
    needs: [test-api, docker-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c api/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_API }}
      - if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          channel-id: alerts
          payload: |
            {
              "text": "Deployment of `${{ github.event.repository.name }}` failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Deployment of `${{ github.event.repository.name }}` failed>*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  lint-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
